import {
  DANGER_TEXT,
  INK,
  INK_MUTED,
  INK_SECONDARY,
  LITE_BLUE,
  LITE_BLUE_HOVER,
  LITE_BLUE_SOFT,
  LINE,
  LINE_DARK,
  NODE_OFFLINE,
  NODE_OFFLINE_SOFT,
  NODE_ONLINE,
  NODE_ONLINE_SOFT,
  PAGE_DARK,
  PAGE_LIGHT,
  PAPER_DARK,
  PAPER_LIGHT,
  SOFT_DARK,
  SOFT_LIGHT,
  SUCCESS_TEXT,
  TRACK_DARK,
  TRACK_LIGHT,
} from "@/theme/brand"

export const THEME = {
  ink: INK,
  ink2: INK_SECONDARY,
  muted: INK_MUTED,
  blue: LITE_BLUE,
  blueHover: LITE_BLUE_HOVER,
  blueSoft: LITE_BLUE_SOFT,
  coral: NODE_OFFLINE,
  green: NODE_ONLINE,
  greenSoft: NODE_ONLINE_SOFT,
  redSoft: NODE_OFFLINE_SOFT,
  successText: SUCCESS_TEXT,
  dangerText: DANGER_TEXT,
  page: PAGE_LIGHT,
  surface: PAPER_LIGHT,
  surfaceSoft: SOFT_LIGHT,
  line: LINE,
  lineSoft: TRACK_LIGHT,
  barTrack: TRACK_LIGHT,
  disk: "#E4A029",
  darkPage: PAGE_DARK,
  darkSurface: PAPER_DARK,
  darkSurfaceSoft: SOFT_DARK,
  darkLine: LINE_DARK,
  darkLineSoft: TRACK_DARK,
  darkBlueSoft: "#12334A",
  darkGreenSoft: "#143C2B",
  darkBarTrack: TRACK_DARK,
  hero: PAPER_DARK,
} as const

export const RESOURCE_COLORS = {
  cpu: THEME.blue,
  memory: THEME.coral,
  storage: THEME.disk,
} as const

export const PROBE_COLORS = [THEME.blue, THEME.green, THEME.coral, THEME.disk, "#8A56DE", "#74BEF0"] as const
