import assert from "node:assert/strict"
import { existsSync, readFileSync } from "node:fs"
import test from "node:test"

const footer = readFileSync(new URL("../src/components/Footer.tsx", import.meta.url), "utf8")
const serverPage = readFileSync(new URL("../src/pages/Server.tsx", import.meta.url), "utf8")
const groupSwitch = readFileSync(new URL("../src/components/GroupSwitch.tsx", import.meta.url), "utf8")
const languageSwitcher = readFileSync(new URL("../src/components/LanguageSwitcher.tsx", import.meta.url), "utf8")
const i18n = readFileSync(new URL("../src/i18n.ts", import.meta.url), "utf8")
const theme = readFileSync(new URL("../src/theme/createLiteTheme.ts", import.meta.url), "utf8")
const websocket = readFileSync(new URL("../src/context/websocket-provider.tsx", import.meta.url), "utf8")
const liteApi = readFileSync(new URL("../src/lib/lite-api.ts", import.meta.url), "utf8")
const themeHomeSort = readFileSync(new URL("../src/lib/theme-home-sort.ts", import.meta.url), "utf8")

test("limits public languages to Chinese, English and Japanese", () => {
  assert.match(languageSwitcher, /"zh-CN"/)
  assert.match(languageSwitcher, /"zh-TW"/)
  assert.match(languageSwitcher, /"en-US"/)
  assert.match(languageSwitcher, /"ja-JP"/)
  assert.doesNotMatch(languageSwitcher, /ru-RU|es-ES|de-DE|ta-IN/)
  assert.match(i18n, /ja-JP/)
  assert.doesNotMatch(i18n, /ru-RU|es-ES|de-DE|ta-IN/)
})

test("loads only the current public language until the language menu is opened", () => {
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  const main = readFileSync(new URL("../src/main.tsx", import.meta.url), "utf8")
  assert.doesNotMatch(i18n, /import enTranslation from/)
  assert.doesNotMatch(i18n, /import zhCNTranslation from/)
  assert.match(i18n, /import\("\.\/locales\/zh-CN\/translation\.json"\)/)
  assert.match(i18n, /import\("\.\/locales\/zh-TW\/translation\.json"\)/)
  assert.match(i18n, /import\("\.\/locales\/en\/translation\.json"\)/)
  assert.match(i18n, /import\("\.\/locales\/ja\/translation\.json"\)/)
  assert.match(i18n, /export function preloadPublicLocales/)
  assert.match(i18n, /export async function changePublicLanguage/)
  assert.match(i18n, /load: "currentOnly"/)
  assert.match(main, /i18nReady/)
  assert.match(languageSwitcher, /preloadPublicLocales\(\)/)
  assert.match(languageSwitcher, /changePublicLanguage\(code\)/)
  assert.match(app, /readStoredLanguage\(\)/)
  assert.match(app, /changePublicLanguage\(lng, \{ persist: false \}\)/)
})

test("hides homepage sort, version and Ctrl+K", () => {
  const main = readFileSync(new URL("../src/main.tsx", import.meta.url), "utf8")
  const index = readFileSync(new URL("../index.html", import.meta.url), "utf8")
  assert.doesNotMatch(serverPage, /defaultSort/)
  assert.match(serverPage, /readThemeHomeSort/)
  assert.doesNotMatch(footer, /Ctrl|⌘|V1\.0\.0|themeBy/)
  assert.match(footer, /Powered by Lite/)
  assert.match(footer, /mt-3/)
  assert.doesNotMatch(footer, /pt-7|pb-3 pt-3/)
  assert.doesNotMatch(main, /CommandProvider|SortProvider|TooltipProvider|sonner/)
  assert.doesNotMatch(index, /flag-icons|font-logos/)
  assert.equal(existsSync(new URL("../src/lib/geo-json-string.ts", import.meta.url)), false)
  assert.equal(existsSync(new URL("../src/lib/geo-limit.ts", import.meta.url)), false)
  assert.equal(existsSync(new URL("../src/components/ui/command.tsx", import.meta.url)), false)
  assert.equal(existsSync(new URL("../public/animated-man.webp", import.meta.url)), false)
  assert.equal(existsSync(new URL("../src/components/Icon.tsx", import.meta.url)), false)
})

test("uses brand blue and nested group radii", () => {
  const brand = readFileSync(new URL("../src/theme/brand.ts", import.meta.url), "utf8")
  const css = readFileSync(new URL("../src/index.css", import.meta.url), "utf8")
  assert.match(brand, /#078DEE/)
  assert.match(brand, /PAGE_LIGHT = "#F4F6F8"/)
  assert.match(brand, /PAPER_LIGHT = "#FFFFFF"/)
  assert.match(css, /background-color: #f4f6f8/)
  assert.match(css, /--lite-paper: #ffffff/)
  assert.match(theme, /LITE_BLUE/)
  assert.match(theme, /paper: isLight \? PAPER_LIGHT : PAPER_DARK/)
  assert.match(groupSwitch, /const GROUP_RADIUS_PX = 8/)
  assert.match(groupSwitch, /const GROUP_INNER_RADIUS_PX = GROUP_RADIUS_PX - GROUP_PADDING_PX/)
})

test("homepage uses a card-style status overview with a light health gradient", () => {
  const overview = readFileSync(new URL("../src/components/ServerOverview.tsx", import.meta.url), "utf8")
  assert.match(overview, /serverOverview.runningStatus/)
  assert.match(overview, /serverOverview.liveTraffic/)
  assert.match(overview, /rgba\(7,141,238,\.10\)/)
  assert.match(overview, /max-\[967px\]:block/)
  assert.match(overview, /setStatus\("online"\)/)
  assert.match(overview, /setStatus\("offline"\)/)
  assert.match(overview, /setStatus\("all"\)/)
  assert.doesNotMatch(overview, /SYSTEM HEALTH/)
  assert.doesNotMatch(overview, /conic-gradient/)
  assert.match(overview, /minmax\(280px,400px\)_minmax\(220px,320px\)/)
  assert.match(overview, /healthStatusDots\(servers\)/)
  assert.match(overview, /OverviewPane/)
  assert.match(overview, /flex h-5 w-full shrink-0 items-center/)
  assert.match(overview, /flex h-4 w-full shrink-0 items-center/)
  assert.doesNotMatch(overview, /content-center/)
  assert.doesNotMatch(overview, /flex-col justify-between gap-3/)
  assert.match(overview, /axisSpeedTicks/)
  assert.match(overview, /trafficUnit/)
  assert.match(overview, /if \(compact\)/)
  assert.doesNotMatch(overview, /slice\(0, 32\)/)
})

test("homepage latency probes keep latency and packet loss in one compact metric group", () => {
  const latency = readFileSync(new URL("../src/components/ServerLatencySummary.tsx", import.meta.url), "utf8")
  const card = readFileSync(new URL("../src/components/ServerCard.tsx", import.meta.url), "utf8")
  const css = readFileSync(new URL("../src/index.css", import.meta.url), "utf8")
  const planInfo = readFileSync(new URL("../src/components/PlanInfo.tsx", import.meta.url), "utf8")
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  assert.match(latency, /formatProbePacketLoss/)
  assert.match(latency, /readShowHomePacketLoss/)
  assert.match(latency, /serverCard.packetLoss/)
  assert.match(latency, /text-\[10px\] leading-none tabular-nums text-\[#7A8792\]/)
  assert.match(latency, /flex min-w-0 items-baseline justify-between gap-2/)
  assert.match(latency, /flex shrink-0 items-center gap-2/)
  assert.match(latency, /h-2\.5 w-px/)
  assert.match(latency, /leading-none tabular-nums/)
  assert.match(latency, /max-\[967px\]:hidden/)
  assert.match(latency, /mt-1\.5 h-\[5px\] overflow-hidden/)
  assert.doesNotMatch(latency, /flex-col items-end/)
  assert.doesNotMatch(latency, /packetLossTone/)
  assert.doesNotMatch(latency, /稳定/)
  assert.doesNotMatch(latency, /y1="21"|polyline|sparklinePoints|grid-cols-3/)
  assert.match(latency, /h-\[5px\]/)
  assert.doesNotMatch(latency, /homeLatencyGridTemplate/)
  assert.match(latency, /HOME_LATENCY_CARD_LIMIT/)
  assert.match(latency, /slice\(0, HOME_LATENCY_CARD_LIMIT\)/)
  assert.match(latency, /grid-cols-2/)
  assert.match(latency, /col-span-2/)
  assert.match(latency, /stackProbes/)
  assert.match(latency, /data-probe-layout/)
  assert.match(latency, /latencyBarTone/)
  assert.match(latency, /packetFillTone/)
  assert.match(card, /resourceUsageTone/)
  assert.doesNotMatch(latency, /packetLoss \?\? 0\) >= 5/)
  assert.doesNotMatch(planInfo, /regionTag/)
  assert.doesNotMatch(planInfo, /country_code/)
  assert.doesNotMatch(planInfo, /networkRoute/)
  assert.match(card, /flex flex-wrap items-center justify-between gap-x-3/)
  assert.match(card, /lite-server-card/)
  assert.match(card, /border-b border-\[var\(--lite-line\)\]/)
  assert.match(card, /border-t border-\[var\(--lite-line\)\] pt-3\.5/)
  assert.match(css, /html\.dark \.lite-server-card:hover/)
  assert.match(css, /0 0 56px rgba\(7, 141, 238, 0\.12\)/)
  assert.match(css, /0 0 64px rgba\(255, 255, 255, 0\.1\)/)
  assert.doesNotMatch(css, /\.lite-server-card::before/)
  assert.doesNotMatch(css, /0 0 0 1px rgba\(7, 141, 238/)
  assert.doesNotMatch(css, /0 0 16px 2px/)
  assert.doesNotMatch(css, /0 0 72px 18px/)
  assert.doesNotMatch(planInfo, /trafficVol/)
  assert.doesNotMatch(planInfo, /bandwidth/)
  assert.match(planInfo, /extraList/)
  assert.doesNotMatch(app, /PageTransition/)
})

test("header and page body share the same content shell", () => {
  const header = readFileSync(new URL("../src/components/Header.tsx", import.meta.url), "utf8")
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  const css = readFileSync(new URL("../src/index.css", import.meta.url), "utf8")
  assert.match(css, /lite-page-shell/)
  assert.match(css, /max-w-\[2240px\]/)
  assert.match(css, /--lite-header-height: 64px/)
  assert.match(css, /scrollbar-gutter: stable/)
  assert.match(header, /lite-page-shell/)
  assert.match(header, /fixed inset-x-0 top-0/)
  assert.match(app, /lite-page-shell/)
  assert.match(app, /h-\[calc\(var\(--lite-header-height\)\+var\(--safe-area-top\)\)\]/)
  assert.doesNotMatch(header, /max-w-\[1420px\]/)
  assert.doesNotMatch(header, /liveConnection/)
})

test("restores homepage scroll after leaving a server detail page", () => {
  const header = readFileSync(new URL("../src/components/Header.tsx", import.meta.url), "utf8")
  const overview = readFileSync(new URL("../src/components/ServerDetailOverview.tsx", import.meta.url), "utf8")
  const serverCard = readFileSync(new URL("../src/components/ServerCard.tsx", import.meta.url), "utf8")
  assert.match(serverPage, /restoreHomeScroll\(\)/)
  assert.match(serverPage, /saveHomeScroll\(\)/)
  assert.match(serverPage, /addEventListener\("scroll"/)
  assert.match(serverCard, /saveHomeScroll\(\)/)
  assert.match(header, /clearHomeScroll\(\)/)
  assert.match(overview, /navigate\("\/"\)/)
})

test("public PWA uses cover viewport and root safe-area insets", () => {
  const index = readFileSync(new URL("../index.html", import.meta.url), "utf8")
  const header = readFileSync(new URL("../src/components/Header.tsx", import.meta.url), "utf8")
  const css = readFileSync(new URL("../src/index.css", import.meta.url), "utf8")
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  assert.match(index, /viewport-fit=cover/)
  assert.match(index, /lite-standalone/)
  assert.match(index, /apple-mobile-web-app-status-bar-style" content="black-translucent"/)
  assert.match(index, /rel="apple-touch-icon" href="\/apple-touch-icon\.png/)
  assert.match(css, /--safe-area-top: 0px/)
  assert.match(css, /display-mode: standalone/)
  assert.match(css, /html\.lite-standalone/)
  assert.match(css, /--safe-area-top: env\(safe-area-inset-top, 0px\)/)
  assert.match(header, /pt-\[var\(--safe-area-top\)\]/)
  assert.match(header, /backdrop-blur-sm/)
  assert.match(header, /bg-white\/96/)
  assert.match(app, /var\(--safe-area-bottom\)/)
})

test("applies homepage sort from theme settings", () => {
  assert.match(themeHomeSort, /HomeSortType/)
  assert.match(themeHomeSort, /HomeSortOrder/)
  assert.match(serverPage, /aria-label=\{t\("home.sort"\)\}/)
  assert.match(serverPage, /flex min-w-0 items-center gap-3 max-\[967px\]:contents/)
  assert.match(serverPage, /flex items-end gap-2.5/)
  assert.match(serverPage, /text-\[11px\] leading-none text-\[#919EAB\]/)
  assert.doesNotMatch(serverPage, /top-1\.5/)
})

test("keeps public dashboard polling cheap", () => {
  assert.match(websocket, /STATUS_POLL_MS = 5000/)
  assert.match(websocket, /getLiteNodes\(false\)/)
  assert.match(websocket, /readLiveStatusCache/)
  assert.match(websocket, /writeLiveStatusCache/)
  assert.doesNotMatch(websocket, /messageHistory|HISTORY_LIMIT|needReconnect/)
  assert.match(liteApi, /public:getPingMetricStats/)
  assert.match(liteApi, /historyMaxPoints/)
  assert.match(serverPage, /refetchInterval: 5_000/)
  assert.match(serverPage, /homeProbeShouldStack/)
  assert.match(serverPage, /stackLatencyProbes/)
})

test("drops unused public-dashboard leftovers", () => {
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  const header = readFileSync(new URL("../src/components/Header.tsx", import.meta.url), "utf8")
  const main = readFileSync(new URL("../src/main.tsx", import.meta.url), "utf8")
  const chart = readFileSync(new URL("../src/components/ui/chart.tsx", import.meta.url), "utf8")
  const sortContext = readFileSync(new URL("../src/context/sort-context.ts", import.meta.url), "utf8")
  const formatInfo = readFileSync(new URL("../src/lib/utils.ts", import.meta.url), "utf8")
  assert.doesNotMatch(app, /RefreshToast/)
  assert.doesNotMatch(header, /RefreshToast|needReconnect/)
  assert.doesNotMatch(main, /url="\/api\/v1\/ws\/server"/)
  assert.doesNotMatch(chart, /ChartLegend/)
  assert.doesNotMatch(sortContext, /createContext|SortContext/)
  assert.doesNotMatch(formatInfo, /boot_time_string|gpu_info/)
  assert.doesNotMatch(formatInfo, /export const fetcher|liteFetcher|formatRelativeTime/)
  assert.doesNotMatch(sortContext, /up total|down total/)
  assert.doesNotMatch(readFileSync(new URL("../src/lib/sparkline.ts", import.meta.url), "utf8"), /sparklinePoints|padLeft/)
  assert.doesNotMatch(readFileSync(new URL("../src/lib/region.ts", import.meta.url), "utf8"), /regionTone/)
  assert.doesNotMatch(readFileSync(new URL("../src/lib/home-latency.ts", import.meta.url), "utf8"), /HOME_PAGE_MAX_WIDTH|HOME_CARD_GAP|HOME_CARD_MIN_WIDTH/)
  assert.doesNotMatch(themeHomeSort, /THEME_HOME_SORT_TYPES/)
  assert.equal(existsSync(new URL("../src/lib/theme-colors.ts", import.meta.url)), false)
  assert.equal(existsSync(new URL("../src/components/RemainPercentBar.tsx", import.meta.url)), false)
})

test("shows a loader instead of a blank page while public settings load", () => {
  const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8")
  const loader = readFileSync(new URL("../src/components/loading/Loader.tsx", import.meta.url), "utf8")
  const css = readFileSync(new URL("../src/index.css", import.meta.url), "utf8")
  assert.match(app, /<Header \/>/)
  assert.match(app, /!settingData \? \(\s*<Loader visible \/>/)
  assert.match(app, /useLayoutEffect/)
  assert.doesNotMatch(app, /isCustomCodeInjected/)
  assert.doesNotMatch(app, /if \(!settingData\) \{\s*return null/)
  assert.doesNotMatch(app, /fullscreen/)
  assert.match(loader, /CircularProgress/)
  assert.match(loader, /size=\{44\}/)
  assert.match(loader, /#078DEE/)
  assert.match(loader, /common\.loading/)
  assert.match(loader, /flex-1/)
  assert.doesNotMatch(loader, /fullscreen/)
  assert.doesNotMatch(loader, /min-h-dvh/)
  assert.doesNotMatch(css, /hamster-loading/)
  assert.doesNotMatch(loader, /hamster-spinner/)
})

test("keeps assigned ping tasks on the public monitor even without metric points", () => {
  assert.match(liteApi, /mergeAssignedPingMonitors/)
  assert.match(liteApi, /unionPingTasksForClient/)
  assert.match(liteApi, /seedAssignedHomeLatency/)
})

test("prefetches probe charts from homepage hover, press and visibility", () => {
  const latency = readFileSync(new URL("../src/components/ServerLatencySummary.tsx", import.meta.url), "utf8")
  const card = readFileSync(new URL("../src/components/ServerCard.tsx", import.meta.url), "utf8")
  const chart = readFileSync(new URL("../src/components/NetworkChart.tsx", import.meta.url), "utf8")
  const prefetch = readFileSync(new URL("../src/lib/prefetch-monitor.ts", import.meta.url), "utf8")
  assert.match(prefetch, /prefetchQuery/)
  assert.match(prefetch, /priority/)
  assert.match(prefetch, /MAX_IDLE_PREFETCH = 1/)
  assert.match(latency, /IntersectionObserver/)
  assert.match(latency, /onPointerEnter/)
  assert.match(latency, /onPointerDown/)
  assert.match(latency, /prefetchRef\.current\?\.\(false\)/)
  assert.match(card, /prefetchServerMonitor/)
  assert.match(card, /prefetchMonitor\(true\)/)
  assert.match(chart, /monitorQueryKey/)
  assert.match(chart, /readHomeLatencyCache/)
  assert.match(chart, /waitingForChart/)
})

test("public locales share the visitor-facing copy keys", () => {
  function flatten(obj: Record<string, unknown>, prefix = ""): string[] {
    return Object.entries(obj).flatMap(([key, value]) => {
      const path = prefix ? `${prefix}.${key}` : key
      return value && typeof value === "object" && !Array.isArray(value)
        ? flatten(value as Record<string, unknown>, path)
        : [path]
    })
  }
  const locales = ["zh-CN", "zh-TW", "en", "ja"]
  const trees = locales.map((locale) => JSON.parse(readFileSync(new URL(`../src/locales/${locale}/translation.json`, import.meta.url), "utf8")))
  const keys = trees.map((tree) => flatten(tree).sort())
  for (let i = 1; i < keys.length; i++) {
    assert.deepEqual(keys[i], keys[0], `${locales[i]} keys differ from zh-CN`)
  }
  for (const required of [
    "home.allServers",
    "home.serverCount",
    "serverCard.cumulative",
    "serverDetail.backToList",
    "serverOverview.runningStatus",
    "monitor.overview",
    "region.asia",
    "traffic.resetToday",
    "privateSite.title",
    "common.loading",
  ]) {
    const value = required.split(".").reduce((node: unknown, part) => (node as Record<string, unknown>)?.[part], trees[0])
    assert.equal(typeof value, "string", `zh-CN missing ${required}`)
  }
  assert.equal(keys[0].includes("map.Distributions"), false)
  assert.equal(keys[0].includes("TypeCommand"), false)
  assert.equal(keys[0].includes("serviceTracker.noService"), false)
  assert.equal(trees[0].home.liveUpdate, "数据每5S更新")
  assert.match(trees[1].home.liveUpdate, /5S/)
  assert.match(trees[2].home.liveUpdate, /5s/)
  assert.match(trees[3].home.liveUpdate, /5秒/)
})
